/** 
 * Dynamic calculation is a bit harder to do for support that's why added static values for every condition accordingly
 */
import { DoorSwingMatrix, SupportMatrix } from "@/types/calculations";

export const SUPPORT_LEFT: SupportMatrix = {
  "20": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -2.44,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.75,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -2.24,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.65,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -1.60,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.35,
    },
  },
  "22": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -1.82,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.55,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -1.62,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.45,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -1.30,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.25,
    },
  },
  "24": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -1.48,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.45,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -1.32,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.35,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.80,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.10,
    },
  },
  "26": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.88,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.25,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.82,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.20,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.15,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.9,
    },
  },
  "28": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.48,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.15,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.52,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.10,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.15,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.8,
    },
  },
  "30": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.05,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.12,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.90,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.63,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.65,
    },
  },
  "34": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.05,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.12,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.90,
    },
    adaLeft: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: -0.55,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.38,
    },
    adaRight: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: 0.40,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.63,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.65,
    },
  },
  "36": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.05,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.12,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.90,
    },
    adaLeft: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: -0.18,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.28,
    },
    adaRight: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: 0.70,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.9,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.63,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.65,
    },
  },
}

export const SUPPORT_RIGHT: SupportMatrix = {
  "20": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: 1.60,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.45,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 1.80,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.60,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 1.48,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.35,
    },
  },
  "22": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: 1.30,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.35,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 1.90,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.65,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 1.18,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.30,
    },
  },
  "24": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.85,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.20,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 1.20,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.40,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.63,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.05,
    },
  },
  "26": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.30,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.00,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.80,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.25,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.20,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.90,
    },
  },
  "28": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.30,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.00,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.50,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.15,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.22,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.75,
    },
  },
  "30": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.28,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.80,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.18,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.90,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.70,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.58,
    },
  },
  "34": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.28,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.80,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.18,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.90,
    },
    adaLeft: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: 0.05,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.15,
    },
    adaRight: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: 0.70,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.48,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.70,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.58,
    },
  },
  "36": {
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.28,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.80,
    },
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.18,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.90,
    },
    adaLeft: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: -0.15,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.10,
    },
    adaRight: {
      positionX: 0.0574,
      positionY: 0,
      positionZ: 0.50,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1.38,
    },
    default: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.70,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 0.58,
    },
  },
}

export const DOOR_SWING: DoorSwingMatrix = {
  "20": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.84,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.84,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  },
  "22": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.72,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.76,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  },
  "24": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.54,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.58,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  },
  "26": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.40,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.36,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  },
  "28": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.24,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.28,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  },
  "30": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.08,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.12,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  },
  "34": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.65,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.48,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  },
  "36": {
    right: {
      positionX: 0,
      positionY: 0,
      positionZ: 0.55,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    },
    left: {
      positionX: 0,
      positionY: 0,
      positionZ: -0.33,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
    }
  }
};
